# Generated by Django 2.2.4 on 2020-01-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('oily', models.CharField(choices=[('O', '유익함'), ('', '영향없음'), ('X', '유해')], max_length=10)),
                ('dry', models.CharField(choices=[('O', '유익함'), ('', '영향없음'), ('X', '유해')], max_length=10)),
                ('sensitive', models.CharField(choices=[('O', '유익함'), ('', '영향없음'), ('X', '유해')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('ingredients', models.CharField(blank=True, max_length=254)),
                ('monthlySales', models.IntegerField()),
                ('oilyScore', models.IntegerField(blank=True, null=True)),
                ('dryScore', models.IntegerField(blank=True, null=True)),
                ('sensitiveScore', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
